In [4]:
# learning numpy

import numpy as np

np_arr = np.arange(100)
print(np_arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [6]:

# creating numpy arrays

a = [1,2,3]
b = np.array(a)

print(b)
print(type(b))



[1 2 3]
<class 'numpy.ndarray'>


In [11]:
a = [1,2,3,'5',1.7]

b = np.array(a,dtype = float)
print(b)

[1.  2.  3.  5.  1.7]


In [13]:
a = [1,2,3,'5',1.7]

b = np.array(a*3,dtype=int)
print(b)

[1 2 3 5 1 1 2 3 5 1 1 2 3 5 1]


In [15]:

# more functions

b = np.ones(3,dtype=int)
print(b)



[1 1 1]


In [18]:
b = np.zeros(3,dtype=int)
print(b)
b

[0 0 0]


array([0, 0, 0])

In [20]:
b = np.ones((2,3),dtype=int)
print(b)

[[1 1 1]
 [1 1 1]]


In [22]:
b = np.zeros((3,4),dtype=int)
print(b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
b = np.full(3,5)
print(b)

[5 5 5]


In [25]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = np.arange(2,10)
b


array([2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b = np.arange(2,10,2)
b

array([2, 4, 6, 8])

In [31]:
b = np.linspace(2,10)
b
print(b[1]-b[0])
print(b[3]-b[2])

0.16326530612244916
0.16326530612244916


In [34]:
b = np.linspace(2,10,5,dtype = int,endpoint = False)
b

array([2, 3, 5, 6, 8])

In [35]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [41]:
b = np.random.rand(3)
b

array([0.48304562, 0.95571145, 0.63733327])

In [42]:
b = np.random.rand(3,5)
b

array([[0.70481594, 0.62617589, 0.37728015, 0.77483398, 0.52853986],
       [0.47263553, 0.82241362, 0.52430197, 0.67851555, 0.44669648],
       [0.65871536, 0.82797554, 0.15175881, 0.13545517, 0.21715738]])

In [43]:
b = np.random.rand(10)*10
b

array([9.92475861, 8.69825215, 3.99370494, 0.69787799, 4.03345394,
       4.63003016, 4.85872242, 4.11215699, 7.23106922, 8.38084531])

In [44]:
b = np.random.randint(10, size = (4, 4))
b

array([[9, 9, 7, 6],
       [9, 6, 2, 9],
       [2, 6, 1, 7],
       [3, 0, 8, 2]])

In [45]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)


[1, 2, 3, 4, 5]
[ 6 13  8  9 14]
[ 7 15 11 15 17]


In [46]:
a = a+1
print(a)


[ 7 14  9 10 15]


In [47]:
a = a*b
print(a)

[ 49 210  99 150 255]


In [48]:
g = a//b


In [49]:
print(g)

[ 7 14  9 10 15]


In [50]:
h = a**b
h

array([        678223072849,  3549789509819072512,  6711666838031917339,
       -2705209260063490048, -4053201496744390401])

In [52]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[ 49 210  99 150 255]
763
152.6
49
0
255
4


In [53]:
print(a)
print(b)


[ 49 210  99 150 255]
[ 7 15 11 15 17]


In [54]:
a > b

array([ True,  True,  True,  True,  True])

In [55]:
b > a


array([False, False, False, False, False])

In [56]:
a == b

array([False, False, False, False, False])

In [57]:
print(np.logical_or(a,b))

print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [60]:
a[2] = 0
print(a)
print(np.logical_not(a))

[ 49 210   0 150 255]
[False False  True False False]


In [63]:
print(b)
bool_arr = b > 10
print(bool_arr)


[ 7 15 11 15 17]
[False  True  True  True  True]


In [79]:
new_arr = b[bool_arr]
print(new_arr)



[   19    19    15 20000]


In [78]:
new_arr = b[b>10]
print(new_arr)



[   19    19    19    15 20000]


In [77]:
new_arr = b[(b>10) & (b<17)]
new_arr



array([15])

In [75]:
print(b)



[20000 20000 20000    15 20000]


In [68]:
c = b
c

array([ 7, 15, 11, 15, 17])

In [76]:
c[:3] = 19

c


array([   19,    19,    19,    15, 20000])

In [70]:
print(b)
print(c)

[19 19 19 15 17]
[19 19 19 15 17]


In [73]:
c[c<15] = 20000
print(c)



[20000 20000 20000    15 20000]


In [80]:
print(b)

[   19    19    19    15 20000]


In [81]:
print(b[b==19])

[19 19 19]


In [82]:
indexes = np.where(b == 19)
print(indexes)


(array([0, 1, 2]),)


In [83]:
print(a)
print(b)


[ 49 210   0 150 255]
[   19    19    19    15 20000]


In [85]:
ind = np.where(b == 15)
print(ind)
print(a[ind])

(array([3]),)
[150]


In [88]:
a = np.random.randint(10,size=(10))

In [89]:
a


array([5, 8, 1, 0, 5, 6, 2, 4, 9, 4])

In [90]:

a = np.arange(10)

print(a[a%3==0])

[0 3 6 9]


In [91]:
# boolean indexing


a = np.random.randint(1,30,(5,6))

print(a)


[[11 24  3 27 26 16]
 [22 17 28 27 24 26]
 [ 1  6 25 27 28 29]
 [20 15 22 14 10 11]
 [11  2 19 23  5 19]]


In [93]:
bool_arr = a > 20
print(bool_arr)

[[False  True False  True  True False]
 [ True False  True  True  True  True]
 [False False  True  True  True  True]
 [False False  True False False False]
 [False False False  True False False]]


In [94]:
ans = a[bool_arr]
print(ans)

[24 27 26 22 28 27 24 26 25 27 28 29 22 23]


In [95]:
b = a
print(a)

[[11 24  3 27 26 16]
 [22 17 28 27 24 26]
 [ 1  6 25 27 28 29]
 [20 15 22 14 10 11]
 [11  2 19 23  5 19]]


In [96]:
b[bool_arr] = 100
print(b)

[[ 11 100   3 100 100  16]
 [100  17 100 100 100 100]
 [  1   6 100 100 100 100]
 [ 20  15 100  14  10  11]
 [ 11   2  19 100   5  19]]


In [97]:
c = np.random.randint(1,10,(2,2))
print(c)

[[7 6]
 [5 1]]


In [99]:
c_bool = np.array([[True,False],[False,True],[True,True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [101]:
# print(c[c_bool])

In [102]:
print(b)

[[ 11 100   3 100 100  16]
 [100  17 100 100 100 100]
 [  1   6 100 100 100 100]
 [ 20  15 100  14  10  11]
 [ 11   2  19 100   5  19]]


In [103]:
bool_arr = b[:,3] == 100

In [107]:
print(bool_arr)
b[bool_arr,3] = 2
print(b)

[ True  True  True False  True]
[[  2   2   2   2   2   2]
 [  2   2   2   2   2   2]
 [  2   2   2   2   2   2]
 [ 20  15 100  14  10  11]
 [  2   2   2   2   2   2]]


In [106]:
b[bool_arr,3] = 2
print(b)

[[  2   2   2   2   2   2]
 [  2   2   2   2   2   2]
 [  2   2   2   2   2   2]
 [ 20  15 100  14  10  11]
 [  2   2   2   2   2   2]]


In [108]:
#numpy broadcasting

'''
if the dimensions of 2 arrays are not same, then we cant use mathematical
operators so we numpy broadcasting comes into picture
'''

x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)


[[1 9 3]
 [8 7 3]
 [3 8 8]]
[[4 9 5]
 [5 7 5]
 [2 1 2]]


In [109]:
ans = x - y
print(ans)

[[-3  0 -2]
 [ 3  0 -2]
 [ 1  7  6]]


In [110]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))
print(x)
print(y)

[[7 4 2]
 [1 4 2]
 [1 2 2]]
[2 9 8]


In [111]:
ans = x - y
print(ans)

[[ 5 -5 -6]
 [-1 -5 -6]
 [-1 -7 -6]]


In [112]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))
print(x)
print(y)

[[2 9]
 [1 6]
 [2 3]]
[[1 9 3]
 [4 3 8]]


In [114]:
y = np.transpose(y)
ans = x-y
print(ans)

[[ 1  5]
 [-8  3]
 [-1 -5]]
